name: build

on:
  workflow_dispatch:
  pull_request:
    
env:
    DOTNETVERSION: 9.0.x
    MAJORVERSION: 1.0.0

jobs:
  buildLibrary:
    runs-on: macOS-26
    outputs:
      output1: ${{ steps.versionstep.outputs.versionnumber }}
    
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
            dotnet-version: ${{env.DOTNETVERSION}}

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/App/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - uses: actions/cache@v3
        with:
          path: ~/.dotnet/workload-manifests
          key: maui-${{ runner.os }}-${{ hashFiles('**/*.xml') }}
          restore-keys: |
            maui-${{ runner.os }}-

      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet workload install maui
      
      - name: Set VERSION variable from tag
        id: versionstep
        run: |
          echo "VERSION=$MAJORVERSION-$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "versionnumber=$MAJORVERSION-$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
    
      - name: Restore nuget packages
        run: |
          dotnet restore App/App.csproj
          dotnet restore AppTest/AppTest.csproj

      - name: Build App and Test
        run: |
          dotnet build App/App.csproj -f net9.0-maccatalyst -c Release
          dotnet test AppTest/AppTest.csproj


