name: build_and_test

on:
  workflow_dispatch:
  pull_request:
    
env:
    DOTNETVERSION: 9.0.x
    MAJORVERSION: 1.0.0

jobs:
  buildLibrary:
    runs-on: macOS-26
    
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
            dotnet-version: ${{env.DOTNETVERSION}}
            
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
           ${{ runner.os }}-nuget

      - uses: actions/cache@v3
        with:
          path: |
            ~/.dotnet/sdk-manifests
            ~/.dotnet/packs
          key: ${{ runner.os }}-maui-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-maui
      
      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet workload install maui

      - name: Set VERSION variable from tag
        id: versionstep
        run: |
          echo "VERSION=$MAJORVERSION-$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "versionnumber=$MAJORVERSION-$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
    
      - name: Restore nuget packages
        run: |
          dotnet restore App/App.csproj
          dotnet restore AppTest/AppTest.csproj

      - name: Build App and Test
        run: |
          dotnet build App/App.csproj -f net9.0-maccatalyst -c Release
          dotnet test AppTest/AppTest.csproj


